<?php
namespace repository;

/**
 * EntradaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntradaRepository extends \Doctrine\ORM\EntityRepository {

    public function findByDate($data) {
        $dql = "SELECT e FROM model\Entrada e INNER JOIN e.data d WHERE d.data = :data";
        $query = $this->_em->createQuery($dql);
        $query->setParameter("data", $data);
        return $query->getResult();
    }
}
