<?php

namespace repository;

/**
 * LocalitzacioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalitzacioRepository extends \Doctrine\ORM\EntityRepository
{
}
