<?php

namespace repository;

/**
 * PagamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagamentRepository extends \Doctrine\ORM\EntityRepository
{
}
