<?php 
$menuDeNavegacio = array( "1" => "Principal", "2" => "Proyectos", "3" => "Ejercicios", "4" => "Llibro de visitas", "5" => "Contacta", "98" => "Registrate", "99" => "Accede");
define('LABEL_BIENVENIDA','Bienvenidos a la mi página web.');

define("MAIN_H1","Lorem Ipsum");
define("MAIN_H3","Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...");
define("MAIN_H5","No hay nadie que ame el dolor mismo, que lo busque y que quiera tenerlo, simplemente porque es dolor ...");
define("MAIN_text","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed est felis, sollicitudin sit amet mollis quis, blandit vel quam. Morbi lacinia ipsum at aliquam luctus. Ut risus nulla, molestie ac lobortis vel, ultricies ut felis. Praesent mattis quis eros ac ultrices. Nunc nec nulla et purus interdum consectetur ut sit amet risus. Duis vel justo dui. Nulla libero nisi, hendrerit sit amet sem posuere, convallis dictum tellus. Ut tincidunt enim dolor, sit amet congue nunc rutrum nec. Vestibulum egestas tempus mi nec malesuada. In convallis lobortis posuere.
Donec vestibulum neque id ipsum congue interdum. Etiam facilisis ligula libero, ut facilisis enim porta sit amet. Aliquam viverra nisl sit amet ultricies interdum. Phasellus tempor nisl justo, non tristique lorem faucibus eget. Fusce blandit placerat lacus, dapibus volutpat urna. Nam interdum, nunc nec euismod ornare, mauris nunc sollicitudin libero, eleifend venenatis lacus massa at magna. Quisque nec sem vel tellus convallis pharetra in id velit. Donec ut purus rutrum, tempor nulla quis, aliquam lectus. Sed mollis sagittis purus, sit amet mollis tortor aliquet et.
Curabitur porta lorem nulla, ac tempor orci maximus eget. Curabitur nec ante nibh. Donec porttitor lectus non est pellentesque, quis placerat diam varius. Maecenas et felis sit amet dolor cursus vestibulum. Nulla imperdiet sem at tellus pulvinar semper. Proin hendrerit lorem urna, ac aliquet magna pretium at. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi purus nibh, varius nec elit id, porttitor gravida nibh. Nam eu semper tellus, at pretium nisi.
Duis et tincidunt est. Donec purus nibh, fermentum quis tellus vel, bibendum suscipit dui. Aliquam turpis ante, dapibus sed turpis pharetra, imperdiet sollicitudin erat. Praesent sed iaculis enim, sit amet mollis arcu. In sed metus ut ipsum tempor pulvinar quis at dolor. Vestibulum ultricies tortor fermentum sem facilisis accumsan. Aliquam ultricies elit purus, eu semper velit pulvinar quis. Maecenas magna urna, bibendum at gravida eu, commodo non tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin aliquet viverra tellus, id lacinia magna maximus vitae. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus ut purus dui. Sed sit amet dui eu ligula dapibus aliquam. Integer ut justo velit.
Vivamus et porttitor dui, ut feugiat massa. Praesent et dapibus elit, blandit tincidunt sem. Donec sit amet nisl interdum, vehicula nunc vulputate, gravida eros. Nulla vehicula commodo nisi, dignissim tristique odio tincidunt sit amet. Nunc tincidunt dapibus nibh non dictum. Vivamus eu turpis purus. Integer sit amet sagittis diam.
Nam faucibus maximus metus, at congue dui varius non. Donec a aliquet lorem. Proin pretium sem eu tortor aliquam accumsan. Vivamus varius, nisl blandit accumsan scelerisque, nunc neque ultrices velit, eget dignissim massa odio a tellus. Nulla ipsum neque, tristique at tortor scelerisque, volutpat gravida nulla. Mauris eu tristique lectus, eget consequat ante. Nullam condimentum velit eu eros dignissim condimentum. Nullam tortor quam, ultrices non varius ac, posuere vitae est. Cras nisi eros, suscipit sit amet pharetra eget, vestibulum et arcu. Suspendisse suscipit, felis semper ultricies viverra, leo magna elementum enim, id convallis mi augue quis lacus. Maecenas facilisis risus in ligula tincidunt sodales. Vivamus nec elit vel libero congue sollicitudin in id leo. Proin auctor ante quis ligula aliquam egestas. Morbi turpis elit, pretium ut efficitur ac, auctor nec est.
");

?>