<?php

namespace Frases\Repository;

/**
 * TemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemaRepository extends \Doctrine\ORM\EntityRepository {
    public function informacio() {
        return $this
        ->createQueryBuilder('t')
        ->select('t.nombre', 'COUNT(f.id) as num')
        ->leftJoin('t.frases', 'f')
        ->groupBy('t.id')
        ->getQuery()
        ->getResult();
    }
}
